import type { SellerHomeDashboard } from "@/features/seller-home/model/seller-home-types";

export const sellerHomeDashboardFixture = {
  dateLabel: "2026년 8월 17일",
  weekDays: ["일", "월", "화", "수", "목", "금", "토"],
  dateCells: [
    { date: "2026-08-16", label: "16", disabled: true },
    { date: "2026-08-17", label: "17", selected: true },
    { date: "2026-08-18", label: "18" },
    { date: "2026-08-19", label: "19" },
    { date: "2026-08-20", label: "20" },
    { date: "2026-08-21", label: "21" },
    { date: "2026-08-22", label: "22" },
  ],
  todayPickupCount: 3,
  waitingInquiryCount: 2,
  pickups: [
    {
      id: "pickup-1",
      inquiryId: "inquiry-1",
      pickupDate: "2026-08-19",
      pickupTime: "오후 02:00",
      customerName: "김지현",
      customerMaskedName: "김지현 님",
      totalPrice: 64000,
      imageUrl: "/seller-home/cake-flower.png",
      status: "PICKUP_READY",
    },
    {
      id: "pickup-2",
      inquiryId: "inquiry-2",
      pickupDate: "2026-08-19",
      pickupTime: "오후 03:30",
      customerName: "박서연",
      customerMaskedName: "박서연 님",
      totalPrice: 71500,
      imageUrl: "/seller-home/cake-berries.png",
      status: "PICKUP_READY",
    },
    {
      id: "pickup-3",
      inquiryId: "inquiry-1",
      pickupDate: "2026-08-19",
      pickupTime: "오후 06:00",
      customerName: "이도현",
      customerMaskedName: "이도현 님",
      totalPrice: 54000,
      imageUrl: "/seller-home/cake-box.png",
      status: "PICKUP_READY",
    },
  ],
  inquiries: [
    {
      id: "inquiry-1",
      customerMaskedName: "이OO",
      previewMessage: "안녕하세요. 잘 부탁드립니다@",
      sentAt: "오후 4:52",
      unreadCount: 1,
      orderFormSubmissionId: "submission-1",
    },
    {
      id: "inquiry-2",
      customerMaskedName: "김OO",
      previewMessage: "안녕하세요.4시 픽업 가능한가요?",
      sentAt: "오후 5:52",
      unreadCount: 1,
      orderFormSubmissionId: null,
    },
  ],
  orderForm: {
    customerName: "김지현",
    customerPhone: "010-0000-0000",
    pickupDateLabel: "8월 19일 수요일",
    pickupTimeLabel: "오후 3:30",
    totalPrice: 58000,
    items: [
      {
        id: "size",
        label: "사이즈",
        value: "1호 (15cm/높이 7cm)",
        priceLabel: "+ 38,000원 ~",
        required: true,
      },
      {
        id: "shape",
        label: "모양",
        value: "1호 (15cm/높이 7cm)",
        priceLabel: "+ 38,000원 ~",
        required: true,
      },
      {
        id: "design",
        label: "케이크 디자인",
        value: "1호 (15cm/높이 7cm)",
        priceLabel: "+ 38,000원 ~",
      },
      {
        id: "packaging",
        label: "포장 방식",
        value: "1호 (15cm/높이 7cm)",
        priceLabel: "+ 38,000원 ~",
        required: true,
      },
      {
        id: "requests",
        label: "기타 요청사항",
        value: "1호 (15cm/높이 7cm)",
        priceLabel: "+ 38,000원 ~",
      },
    ],
  },
  chat: {
    storeName: "위하다",
    info: "픽업만 가능 · 월~일 오후 12:00–17:00",
    statusLabel: "접수대기",
    dateLabel: "8월 14일 금요일",
  },
} satisfies SellerHomeDashboard;
